In [1]:
from sklearn.preprocessing import LabelEncoder

fruits = ['사과', '블루베리', '바나나', '귤', '블루베리', '바나나', '바나나', '사과']

# 레이블 인코더 생성
label_encoder = LabelEncoder()
# 레이블 인코딩 적용
fruits_label_encoded = label_encoder.fit_transform(fruits)

print('레이블 인코딩 후 데이터:', fruits_label_encoded)

레이블 인코딩 후 데이터: [3 2 1 0 2 1 1 3]


In [2]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

fruits = ['사과', '블루베리', '바나나', '귤', '블루베리', '바나나', '바나나', '사과']

# 레이블 인코더, 웟-핫 인코더 생성
label_encoder = LabelEncoder()
onehot_encoder = OneHotEncoder()

# 레이블 인코딩 적용
fruits_label_encoded = label_encoder.fit_transform(fruits)
# 원-핫 인코딩 적용 ---①
fruits_onehot_encoded = onehot_encoder.fit_transform(fruits_label_encoded.reshape(-1, 1))

print('원-핫 인코딩 후 데이터:\n', fruits_onehot_encoded.toarray())

원-핫 인코딩 후 데이터:
 [[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]


In [3]:
onehot_encoder = OneHotEncoder(drop='first')
fruits_onehot_encoded = onehot_encoder.fit_transform(fruits_label_encoded.reshape(-1, 1))

print('원-핫 인코딩 후 첫 번째 열을 제거한 데이터:\n', fruits_onehot_encoded.toarray())

원-핫 인코딩 후 첫 번째 열을 제거한 데이터:
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [4]:
import pandas as pd

pd.get_dummies(fruits)

귤  바나나  블루베리  사과
0  0    0     0   1
1  0    0     1   0
2  0    1     0   0
3  1    0     0   0
4  0    0     1   0
5  0    1     0   0
6  0    1     0   0
7  0    0     0   1